stages:
  - install
  - test

cache:
  paths:
    - node_modules/

default:
  image: mcr.microsoft.com/playwright:v1.43.1-jammy

install_dependencies:
  stage: install
  script:
    - npm ci

run_tests:
  stage: test
  script:
    - npx playwright install --with-deps
    - npx playwright test -c playwright.config.ts --reporter=html
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    reports:
      junit: test-results/test-results.xml