version: 2.1

executors:
  playwright-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-focal
    working_directory: ~/repo

jobs:
  install-dependencies:
    executor: playwright-executor
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install Playwright Browsers
          command: npx playwright install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache/ms-playwright

  run-web-tests:
    executor: playwright-executor
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install Playwright Browsers
          command: npx playwright install
      - run:
          name: Run Playwright web tests
          command: npx playwright test -c playwright.web.config.ts  
      - run:
          name: Generate Allure Report
          command: npm run allure:generate
      - store_artifacts:
          path: allure-report
      - store_test_results:
          path: allure-results

  run-api-tests:
    executor: playwright-executor
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install Playwright Browsers
          command: npx playwright install
      - run:
          name: Run Playwright API tests
          command: npx playwright test -c playwright.api.config.ts  
      - run:
          name: Generate Allure Report
          command: npm run allure:generate
      - store_artifacts:
          path: allure-report
      - store_test_results:
          path: allure-results

workflows:
  web-tests:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only: circleci-project-setup
      - run-web-tests:
          requires:
            - install-dependencies
          filters:
            branches:
              only: circleci-project-setup

  api-tests:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only: circleci-project-setup
      - run-api-tests:
          requires:
            - install-dependencies
          filters:
            branches:
              only: circleci-project-setup