version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.0-browsers
    working_directory: ~/playwright-tests

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Install Playwright Browsers
          command: npx playwright install

  run-playwright-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Playwright Tests
          command: npx playwright test -c playwright.web.config.ts 

workflows:
  test-workflow:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - circleci-project-setup
      - run-playwright-tests:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - circleci-project-setup