name: Playwright Tests

on:
  push:
    branches: [github]

permissions:
  contents: write  # ✅ Required for pushing to gh-pages branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test -c playwright.web.config.ts

      - name: Upload Playwright test report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

  deploy-report:
    needs: test
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download HTML report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./gh-pages-content/playwright-report  # ✅ Move report to subfolder

      - name: Deploy HTML report to GitHub Pages (under sub-path)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-content
          force_orphan: true